Default: &defaults
  database: wt.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: wt_test.sqlite3
  <<: *defaults

Staging:
  database: wt_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: wt_production.sqlite3
  poolsize: 100
  <<: *defaults
